version: "3.8"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - TZ=Asia/Tokyo
    image: walkmlb:dev
    container_name: walkmlb_api
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app:rw
      - /app/.venv
    command: ["uvicorn", "server:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
